import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BreadCrumbs from "@/appComponents/BreadCrumbs/BreadCrumbs";
import Link from "next/link";
import { FaChevronRight } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Component Library for React/Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="header">
          <BreadCrumbs />
          <hr className="headerDivider" />
        </header>
        {children}
        <footer className="footer">
            <hr className="footerDivider"/>
            <div className="footerContentContainer">
              <p className="footerText">Created by • <a href="https://cmillardwebdev.com" className="profileLink">Carl Millard - Web Developer </a>• {new Date().getFullYear()}</p>
              <Link 
                className="repoLink" 
                href="https://github.com/carledwardm/react-component-library/tree/main"
                target="_blank">
                <FaChevronRight className="repoChev"/> Full Repo Link
              </ Link>
            </div>
        </footer>
      </body>
    </html>
  );
}
